//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEATS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEATS()
        {
            this.RESERVATIONS_DETAILS = new HashSet<RESERVATIONS_DETAILS>();
        }
    
        public string ID_SEAT { get; set; }
        public string ID_HALL { get; set; }
        public bool VIP { get; set; }
    
        public virtual HALLS HALLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATIONS_DETAILS> RESERVATIONS_DETAILS { get; set; }
    }
}
